apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms-app
  namespace: hrms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hrms-app
  template:
    metadata:
      labels:
        app: hrms-app
    spec:
      containers:
      - name: hrms-app
        image: 089855661736.dkr.ecr.us-east-1.amazonaws.com/hrms-app:latest
        ports:
        - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /api/employees
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /api/employees
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
