apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hrms-postgres
  namespace: hrms
spec:
  serviceName: hrms-postgres
  replicas: 1
  selector:
    matchLabels:
      app: hrms-postgres
  template:
    metadata:
      labels:
        app: hrms-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/pgdata
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 10Gi
